// <auto-generated />
using System;
using AuctionApp.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuctionApp.API.Migrations
{
    [DbContext(typeof(AuctionDbContext))]
    partial class AuctionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AuctionApp.API.Models.Auction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("StartingPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("WinningBidId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SellerId");

                    b.HasIndex("WinningBidId")
                        .IsUnique();

                    b.ToTable("Auctions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Teléfono en perfecto estado, solo 6 meses de uso. Incluye cargador original, auriculares y caja.",
                            EndDate = new DateTime(2025, 9, 27, 19, 9, 52, 194, DateTimeKind.Local).AddTicks(3478),
                            ImageUrl = "https://images.unsplash.com/photo-1632661674596-df8be070a5c5",
                            SellerId = 1,
                            StartDate = new DateTime(2025, 9, 20, 19, 9, 52, 194, DateTimeKind.Local).AddTicks(3468),
                            StartingPrice = 699.99m,
                            Title = "iPhone 13 Pro Max - Como nuevo"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Consola PS5 Digital Edition en perfecto estado. Incluye 2 mandos DualSense y 3 juegos digitales.",
                            EndDate = new DateTime(2025, 9, 25, 19, 9, 52, 194, DateTimeKind.Local).AddTicks(3489),
                            ImageUrl = "https://images.unsplash.com/photo-1606813907291-d86efa9b94db",
                            SellerId = 1,
                            StartDate = new DateTime(2025, 9, 20, 19, 9, 52, 194, DateTimeKind.Local).AddTicks(3488),
                            StartingPrice = 450m,
                            Title = "PlayStation 5 Digital Edition"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Bicicleta de montaña Trek Marlin 7 talla M. Poco uso, en excelentes condiciones. Ideal para rutas de montaña.",
                            EndDate = new DateTime(2025, 9, 30, 19, 9, 52, 194, DateTimeKind.Local).AddTicks(3491),
                            ImageUrl = "https://images.unsplash.com/photo-1485965120184-e220f721d03e",
                            SellerId = 2,
                            StartDate = new DateTime(2025, 9, 20, 19, 9, 52, 194, DateTimeKind.Local).AddTicks(3491),
                            StartingPrice = 850m,
                            Title = "Bicicleta de montaña Trek Marlin 7"
                        });
                });

            modelBuilder.Entity("AuctionApp.API.Models.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("AuctionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BidTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("BidderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.HasIndex("BidderId");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("AuctionApp.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "usuario1@example.com",
                            Username = "usuario1"
                        },
                        new
                        {
                            Id = 2,
                            Email = "usuario2@example.com",
                            Username = "usuario2"
                        });
                });

            modelBuilder.Entity("AuctionApp.API.Models.Auction", b =>
                {
                    b.HasOne("AuctionApp.API.Models.User", "Seller")
                        .WithMany("Auctions")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuctionApp.API.Models.Bid", "WinningBid")
                        .WithOne()
                        .HasForeignKey("AuctionApp.API.Models.Auction", "WinningBidId");

                    b.Navigation("Seller");

                    b.Navigation("WinningBid");
                });

            modelBuilder.Entity("AuctionApp.API.Models.Bid", b =>
                {
                    b.HasOne("AuctionApp.API.Models.Auction", "Auction")
                        .WithMany("Bids")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuctionApp.API.Models.User", "Bidder")
                        .WithMany("Bids")
                        .HasForeignKey("BidderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("Bidder");
                });

            modelBuilder.Entity("AuctionApp.API.Models.Auction", b =>
                {
                    b.Navigation("Bids");
                });

            modelBuilder.Entity("AuctionApp.API.Models.User", b =>
                {
                    b.Navigation("Auctions");

                    b.Navigation("Bids");
                });
#pragma warning restore 612, 618
        }
    }
}
